TrainDataset:
  !KeypointGroupPoseDataset
    image_dir: train2017
    anno_path: annotations/person_keypoints_train2017.json
    dataset_dir: dataset/coco
    num_joints: 17
    return_mask: False

EvalDataset:
  !KeypointGroupPoseDataset
    image_dir: val2017
    anno_path: annotations/person_keypoints_val2017.json
    dataset_dir: dataset/coco
    num_joints: 17
    test_mode: True
    return_mask: False

TestDataset:
  !ImageFolder
    anno_path: dataset/coco/keypoint_imagelist.txt
    dataset_dir: dataset/coco