epoch: 60

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [50]
    use_warmup: False

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: False
  optimizer:
    type: AdamW
    weight_decay: 0.0001
